//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace karg
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public int ida { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string house { get; set; }
        public string flat { get; set; }
        public Nullable<int> idp { get; set; }
        public Nullable<int> idc { get; set; }
    
        public virtual cafe cafe { get; set; }
        public virtual personal personal { get; set; }
    }
}
