//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace karg
{
    using System;
    using System.Collections.Generic;
    
    public partial class personal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personal()
        {
            this.address = new HashSet<address>();
            this.telephone = new HashSet<telephone>();
        }
    
        public int idp { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string lastname { get; set; }
        public Nullable<System.DateTime> birth { get; set; }
        public Nullable<int> seria_pasport { get; set; }
        public Nullable<int> number_pasport { get; set; }
        public Nullable<int> ids { get; set; }
        public Nullable<int> idc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<address> address { get; set; }
        public virtual cafe cafe { get; set; }
        public virtual work work { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<telephone> telephone { get; set; }
    }
}
