//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace karg
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int idpr { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date_get { get; set; }
        public Nullable<System.DateTime> before_date { get; set; }
        public Nullable<decimal> price { get; set; }
        public string quality { get; set; }
        public string how_much { get; set; }
        public Nullable<int> idsp { get; set; }
        public Nullable<int> idc { get; set; }
    
        public virtual cafe cafe { get; set; }
        public virtual supply supply { get; set; }
    }
}
