//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace karg
{
    using System;
    using System.Collections.Generic;
    
    public partial class telephone
    {
        public int idt { get; set; }
        public string number { get; set; }
        public Nullable<int> idp { get; set; }
    
        public virtual personal personal { get; set; }
    }
}
